### ISSUE TITLE
zig build fails

### ISSUE THREAD

**Issue by wglb** [cryptocode/bio#12]
With version 

```
zig version
0.13.0-dev.75+5c9eb4081
```

typing

`zig build`

in the bio root directory results in the message

```
/home/data2/Build/bio/build.zig:3:21: error: root struct of file 'std' has no member named 'build'
/usr/lib/zig/std/std.zig:1:1: note: struct declared here
```

**Comment by cryptocode** [comment]
Thanks for the report, I've brought main-branch up to date with Zig master (currently rewriting a lot, which happens on a currently-private branch)

**Comment by wglb** [comment]
Thanks! Works for me now.
