### ISSUE TITLE
Intrinsic `append`: isn't this a redundant double-evaluation?

### ISSUE THREAD

**Issue by metaleap** [cryptocode/bio#13]
In this line:

https://github.com/cryptocode/bio/blob/e525af48db08bd4fcc58f6a7f072b4350089fd64/src/intrinsics.zig#L1316

Couldn't it be replaced by `const expr = evaled;`?

**Comment by cryptocode** [comment]
Yeah this might be vestigial code from a refactor, or just a bug. If the first evaluation doesn't yield a list, it's evaluated again, and I don't recall if there ever was a valid case for that.

Note that Bio will be rewritten as a vm interpreter/JIT, so this part will be completely rewritten too. That's longer term though.

If tests pass with your change, feel free to PR!

**Comment by metaleap** [comment]
> Note that Bio will be rewritten as a vm interpreter/JIT

Too cool, looking forward to seeing how that'll be implemented!

> Yeah this might be vestigial code from a refactor

Been there since the first commit — I know since I'm going through the repo's past commits one by one for my own study-ish purposes :grin: finding the code-base very well-done, to my taste :+1:

**Comment by cryptocode** [comment]
Thank you for the kind words! If it's been there since the start, I've long forgotten why 😅  I'll do the change as I think you're right it's redundant.
