### ISSUE TITLE
Another study question: bounds-check here not needed? Or forgotten?  =)

### ISSUE THREAD

**Issue by metaleap** [cryptocode/bio#14]
The lines with _seemingly_ (I could be wrong, maybe it's pre-checked by caller that I've overlooked?) unguarded `[1]` indexing accesses:

https://github.com/cryptocode/bio/blob/15d16a39aa3ad8730926a31bc250ccba74d0cc41/src/intrinsics.zig#L535

https://github.com/cryptocode/bio/blob/15d16a39aa3ad8730926a31bc250ccba74d0cc41/src/intrinsics.zig#L538

https://github.com/cryptocode/bio/blob/15d16a39aa3ad8730926a31bc250ccba74d0cc41/src/intrinsics.zig#L548

**Comment by metaleap** [comment]
Also, separate issue but no separate Issue — missing `requireExactArgCount` in `callable?` and `opaque?` — forgotten or by design?  =)

https://github.com/cryptocode/bio/blob/15d16a39aa3ad8730926a31bc250ccba74d0cc41/src/intrinsics.zig#L455C1-L470C1

**Comment by cryptocode** [comment]
> Also, separate (maybe)issue but no separate Issue — missing requireExactArgCount

Yep, spot on. I'll fix those, thanks!

The quasiquote expansion is already rewritten in a VM branch so I'll skip those.
