### ISSUE TITLE
build errors

### ISSUE THREAD

**Issue by benjiqq** [cryptocode/bio#6]
```
zig version
0.11.0-dev.4183+32a175740

```
the bio binary is zig-out

```
$zig build
$ls zig-out 
total 4384
-rwxr-xr-x  1 ben  staff  2242232 Jul 23 18:12 bio
ben@Bens-MacBook-Air bio % ./zig-out/bio 
ERROR: repl, line 1: File not found: /Users/ben/zigdev/bio/zig-out/std.lisp
Memory leaks detected
error: AlreadyReported
/Users/ben/zigdev/zig-0.11/lib/std/os.zig:5115:19: 0x102c54dfd in realpathZ (bio)
        .NOENT => return error.FileNotFound,
                  ^
/Users/ben/zigdev/zig-0.11/lib/std/os.zig:5085:5: 0x102bfd297 in realpath (bio)
    return realpathZ(&pathname_c, out_buffer);
    ^
/Users/ben/zigdev/bio/src/intrinsics.zig:258:17: 0x102bf2a7a in stdImport (bio)
                return ExprErrors.AlreadyReported;
                ^
/Users/ben/zigdev/bio/src/main.zig:25:13: 0x102bf1f18 in main (bio)
        _ = try intrinsics.stdImport(&interpreter, interpreter.env, args.items);
            ^

```

**Comment by cryptocode** [comment]
This is because `std.lisp` resides on the project root directory, and there's been some recent changes to where Zig puts the binary.

I have a fix for this locally which I'll push soon. This will place the bio executable in the standard `zig-out/bin` directory

**Comment by cryptocode** [comment]
Pushed. You should now be able to run tests like so (from the project root directory):

`zig-out/bin/bio run test.lisp`

And the REPL like so:

`zig-out/bin/bio`

<img width="533" alt="image" src="https://github.com/cryptocode/bio/assets/34946442/1478102b-fb9b-4274-82c6-4e87c015553d">

As for status, I'm currently working on replacing the internal garbage collector with BoehmGC + move from (very slow) interpretation to a virtual machine.
