### ISSUE TITLE
Zig specifics

### ISSUE THREAD

**Issue by benjiqq** [cryptocode/bio#8]
What benefits does a zig implementation  of a LISP have over C/C++ and can bio leverage that?

* package manager?
* wasm target?

**Comment by cryptocode** [comment]
I have made several Lisp implementations in C++, and that works fine. However, I find Zig a vastly better language for interpreter/compiler work. No hidden allocations (ex: std::shared_ptr can heap allocate the control block), no hidden control flow, and the language is so simple that revisiting hobbyist projects like Bio every few months is a breeze. The wasm target will likely be utilized.

I prefer keeping the issue tracker for bug reports and proposals. Feel free to hit me up on the Discord for questions and discussions (you can find me on the Zig discord, feel free to DM me!)
