### ISSUE TITLE
example memory leak

### ISSUE THREAD

**Issue by benjiqq** [cryptocode/bio#9]
all examples print `Memory leaks detected` at the end

```
./bio run examples/hello.lisp
How many times to print Hello?
1
Hello
Memory leaks detected
```

**Comment by cryptocode** [comment]
Interesting, I'm not getting this on macOS, latest Zig trunk. What Zig version/commit are you at?

Either way, I likely won't fix this as I've recently integrated BoehmGC as the root allocator. This will be pushed fairly soon.

**Comment by benjiqq** [comment]
zig version 0.11.0-dev.4183+32a175740

**Comment by cryptocode** [comment]
Pushed initial Boehm GC integration. Let me know if you're able to compile and run the examples.

**Comment by benjiqq** [comment]
works
